name: Terraform & Ansible CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: ap-southeast-2  # Change to your AWS region

jobs:
  deploy:
    name: Terraform & Ansible Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0  # Update if needed

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: .
        run: terraform init

      - name: Terraform Plan
        working-directory: .
        run: terraform plan

      - name: Terraform Apply
        working-directory: .
        run: terraform apply -auto-approve

      - name: Install Ansible
        run: |
          sudo apt update -y
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        working-directory: .
        run: ansible-playbook -i hosts.ini nginx-playbook.yml
